# Generated by Django 3.0 on 2021-07-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('product_category', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('product_image', models.CharField(max_length=350)),
                ('product_ratings', models.FloatField()),
                ('product_review', models.CharField(max_length=300)),
            ],
        ),
    ]
